# Generated by Django 2.1.7 on 2019-03-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0004_productimage_thumbnail")]

    operations = [migrations.RenameField(model_name="product", old_name="is_stock", new_name="in_stock")]
