# Generated by Django 2.1.7 on 2019-03-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0005_auto_20190310_1240")]

    operations = [
        migrations.RemoveField(model_name="producttag", name="products"),
        migrations.AddField(
            model_name="product", name="tags", field=models.ManyToManyField(blank=True, to="main.ProductTag")
        ),
    ]
